---
development:
  cloud_name: desi0mbbg
  api_key: '632665363572649'
  api_secret: IKAHujjBGaEfQAeKpfmTVtk0wYM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: desi0mbbg
  api_key: '632665363572649'
  api_secret: IKAHujjBGaEfQAeKpfmTVtk0wYM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: desi0mbbg
  api_key: '632665363572649'
  api_secret: IKAHujjBGaEfQAeKpfmTVtk0wYM
  enhance_image_tag: true
  static_image_support: false
